import os

# DATABASE DATA
DBUSER = os.environ.get('MYSQL_USER', 'root')
DBPASSWORD = os.environ.get('MYSQL_PASSWORD', 'bebrasus69')
DBHOST = os.environ.get('MYSQL_HOST', 'localhost')
DBPORT = os.environ.get('MYSQL_PORT', '3306')
DBNAME = os.environ.get('MYSQL_DATABASE', 'se_backend')

DBTYPE = "mysql"
DBDRIVER = "pymysql"


# DATABASE USER COLUMNS CONFIG
EMAIL_LENGTH = 32
NAME_LENGTH = 16
PASSWORD_LENGTH = 32
TOKEN_LENGTH = 32


# DATABASE PUBLICATION COLUMNS CONFIG
TEXT_LENGTH = 3000
TITLE_LENGTH = 100
DESCRIPTION_LENGTH = 250


ISDOCKER = os.environ.get("ISDOCKER", 0)


# RECOMENDATIONS CONFIG
PUBL_TIME_SHOWS = 5 # in days